### ISSUE TITLE
Unable to import CSV or XLSX files into OnTask on 3.0.3 

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#100]
We've updated to 3.0.3 but when there appears to be a bug, in importing both XLSX and CSV files.

- CSV file
I tried to upload the same CSV file that I submitted as part of my bug report for issue #99, I get an error indicating that utf8-8 is an unknown encoding (CSV)

What encoding should we now be using?
<img width="575" alt="utf8" src="https://user-images.githubusercontent.com/2507459/47053063-33261700-d160-11e8-86a6-12258920b2c2.png">

- XLSX file:

Uploading this file results in a "System Error" in the Table tab in OnTask v3.0.3. Unlike similar errors before, refreshing does not cause this to disappear

<img width="908" alt="screen shot 2018-10-16 at 4 21 51 pm" src="https://user-images.githubusercontent.com/2507459/47053106-68326980-d160-11e8-9894-b110fcb7166f.png">

I've attached the CSV, XLSX and the entire workflow. 
[report.zip](https://github.com/abelardopardo/ontask_b/files/2485308/report.zip)

P.S.Thanks for all the fast fixes!

**Comment by abelardopardo** [comment]
This is a very strange regression. The word "utf8-8" is not used anywhere in the tool. Thanks for posting the report with the workflow. I'll take a look at it and see if I can replicate the bug.

**Comment by abelardopardo** [comment]
I just tried (production B.3.0.3)

1. Importing  the workflow and "merging" both the CSV and XLSX. No bug found
2. Creating a new workflow and "loading" both the CSV and XSLX. No bug found.

And, as I said in my previous comment, the word "utf8-8" does not appear anywhere in the platform.

The next idea that comes to mind is if you can check, after you get the system error, the file ontask_b/logs/django.log and ontask_b/logs/project.log. These two files collect warnings and errors that are produced during execution. We may have a bit more insight about this glitch.

**Comment by firasm** [comment]
Thanks for trying - after further investigation, it seems the problem is on our end. A modification we made to an unrelated change in a different file caused the problem.

Closing issue. thanks.
