### ISSUE TITLE
Safari UI bug

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#115]
On the action edit page, existing Text Conditions appear far off to the right side of the page in Safari, but are properly centred in Chrome. Screenshots from version B.4.0.0 below.

Safari 12.0.2:
<img width="1680" alt="screen shot 2018-12-19 at 12 25 48 pm" src="https://user-images.githubusercontent.com/6002755/50246374-0376d380-038a-11e9-9a87-31ebbad91d13.png">

Chrome 71.0.3578.98:
![screen shot 2018-12-19 at 12 28 03 pm](https://user-images.githubusercontent.com/6002755/50246393-1093c280-038a-11e9-9898-9245d3588a74.png)

**Comment by abelardopardo** [comment]
Issue fixed in release 4.0
