### ISSUE TITLE
Quick question - api redirecting to http

### ISSUE THREAD

**Issue by radhikavm** [abelardopardo/ontask_b#117]
Hi Abelardo,

Not sure if this a bug but for some odd reason, api calls like /apidoc/#workflow-workflows-list etc are getting called via http instead of https and blocking the output. However if I use postman or alike with https:// they work as expected. I have checked the load balancer settings can't see anything going wrong there. Some help in this regards would be very helpful.

Thanks,
Radhika

**Comment by abelardopardo** [comment]
In principle, the API calls are produced outside the tool, and therefore the choice of HTTP or HTTPS is up to that agent. In production, HTTP requests are not accepted due to security reasons. Make sure the agent that is issuing the API calls uses HTTPS explicitly. That would be my recommendation.
