### ISSUE TITLE
Footer and margins on homepage

### ISSUE THREAD

**Issue by HexaCubist** [abelardopardo/ontask_b#121]
![image](https://user-images.githubusercontent.com/8563277/52829047-2aeee000-3130-11e9-8c1b-1e1893060254.png)

On the homepage with larger screens and shorter content, the footer appears at the end of the body rather than the end of the page.

Additionally, the header container is compacted right up against the navigation. A margin might help here to give it more breathing room.

**Comment by abelardopardo** [comment]
I am not sure I understand you comment. Shouldn't the footer appear at the end of the body? Placing it at the bottom of the screen would appear far removed from the rest of the page.

As for the header, The main idea is to have compact navigation to leave space for the rest, but I'm happy to see some examples of what you mean.

**Comment by abelardopardo** [comment]
Fixed in release B.4.1
