### ISSUE TITLE
Pencil icon on actions list

### ISSUE THREAD

**Issue by HexaCubist** [abelardopardo/ontask_b#122]
![unnamed](https://user-images.githubusercontent.com/8563277/52829193-a94b8200-3130-11e9-93f7-bc38888f28ee.png)

When viewing the actions for a workflow, the pencil icon initially made me think that clicking the name would bring up a renaming dialog (or at least that clicking the pencil would do that). Would it be better to have this as functionality?

**Comment by abelardopardo** [comment]
Clicking means editing. The renaming action has been pushed to the additional operations in the right hand side. The links in the names are present in various locations in the platform and in all those places means "editing". Perhaps removing the icon would make it more explicit?

**Comment by abelardopardo** [comment]
Perhaps we can simply remove the pencil.

**Comment by abelardopardo** [comment]
Fixed in release B.4.1
