### ISSUE TITLE
Card sizing

### ISSUE THREAD

**Issue by HexaCubist** [abelardopardo/ontask_b#123]
![image 1](https://user-images.githubusercontent.com/8563277/52829262-f0397780-3130-11e9-8578-0d9e0e20ee3b.png)

Consider having wider cards as the text is breaking a lot here (3 to a row/300px width looks good?) and making the cards on new rows also size height to fit the previous row (see "Test Overflow").

**Comment by abelardopardo** [comment]
Changed card width to 300px as suggested.

**Comment by abelardopardo** [comment]
Forcing all cards to have the same height is a bit more complex when using a fluid container (not organised by rows, but letting the objects populate various rows)

**Comment by abelardopardo** [comment]
Fixed in release B.4.1
