### ISSUE TITLE
v4 "System error" post fresh install

### ISSUE THREAD

**Issue by dvasjuta** [abelardopardo/ontask_b#126]
I created an Ubuntu 18.04 VM, following these instructions: 
https://github.com/abelardopardo/ontask_b/blob/master/docs_src/Install/index.rst
(The only difference on the VM is Python 3.7 instead of 3.6)

**local.env**

> DEBUG=False
TIME_ZONE=Australia/Melbourne
BASE_URL=''
DOMAIN_NAME=172.16.208.174
SHOW_HOME_FOOTER_IMAGE=True
DATABASE_URL=postgres://ontask:thisIsTheBest@127.0.0.1:5432/ontask
REDIS_URL=redis://127.0.0.1:6379/1
SECRET_KEY=tremor-undercarriage-seattle-forsook
LTI_OAUTH_CREDENTIALS=key=dauphine-zoom-scald-extensor,key2=pinwheel-synapsis-carnal-forklift`

**project.log**
> [18/Feb/2019 16:40:06] DEBUG [/home/mojo/ontask/src/django_auth_lti/middleware_patched.py:46] inside process_request /
[18/Feb/2019 16:40:06] WARNING [/home/mojo/ontask/src/django_auth_lti/middleware_patched.py:199] Could not find LTI launch for resource_link_id None
[18/Feb/2019 16:40:12] DEBUG [/home/mojo/ontask/src/django_auth_lti/middleware_patched.py:46] inside process_request /
[18/Feb/2019 16:40:12] WARNING [/home/mojo/ontask/src/django_auth_lti/middleware_patched.py:199] Could not find LTI launch for resource_link_id None

**curl http://127.0.0.1:8000**
> System error
    Oops! The platform had an internal error. We are sorry. We hope to
    address this anomaly soon.

Let me know if I can provide any other details to assist.

Thanks.

**Comment by dvasjuta** [comment]
![screen shot 2019-02-18 at 4 25 25 pm](https://user-images.githubusercontent.com/9065513/52930389-57a72f80-339c-11e9-9757-e6ea856f78f7.png)

**Comment by abelardopardo** [comment]
Yes. There are some libraries used by the tool that have not been ported yet to Python 3.7, as a consequence, version 3.6 is a must.
