### ISSUE TITLE
Menu icons are confusing

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#127]
In the latest OnTask version, there have been considerable UI improvements to improve readability, navigation, and help guide new instructors through OnTask - great job!

One area there seems to be a bit of regression is the navigation buttons in the top left. There are some inconsistencies, I'll outline them all in one issue, and perhaps they can be split into multiple issues if you agree with the fixes.

1. Problem: When you enter the screen with the list of workflows, it's not entirely clear where you are (in terms of navigation, or how to return to it). 

Fix: Highlight the current tab to ensure that we are in "Home"/"Your Workflows"

![iss1](https://user-images.githubusercontent.com/2507459/53133764-260f9f00-3529-11e9-9450-b1d953943167.png)

2. Clicking "Connections to SQL databases" seems to kick you out of the regular navigation and takes you to another set of menus, with no indication how to get back to the home page with list of workflows.

Fix: Move "SQL connections" to the right of the screen, as this menu item is not workflow specific (all the workflow-related menu items appear on the left. That way it'll stay in the same position whether you're in a workflow or not.

![iss2](https://user-images.githubusercontent.com/2507459/53133858-9cac9c80-3529-11e9-9c9f-d5f91f566522.png)

3. Move "About" and Contact" links to the right of the screen, near "read the manual". I feel that's a more natural place for them, especially because clicking them leads you out of the OnTask app.

4. Once in a workflow, it's very clear where you are at the moment, but you need to hover to figure out what the other icons mean.

Fix: Can the Menu title text exist along with the icons? That way it'll be clear that the message bubbles means "actions". By the way, hover text says 'Messages and Surveys' but the menu title says 'Actions'. I know that those are the same, but most people will just be confused. That is also a convenient fix for the first issue above: leave the text and icon there to let users know what the menus are, and blue background and white text to indicate they're in a particular tab.

![iss3](https://user-images.githubusercontent.com/2507459/53134014-265c6a00-352a-11e9-9d84-07f0f513d844.png)

Let me know what you think. I know these seem minor, and they I can probably train myself to get over it, but if this is the final UI, these changes would be helpful for new users (and those migrating from a previous version).

P.S. We just moved to OnTask v4 so expect a few more issues posted in the next few days.

**Comment by abelardopardo** [comment]
Thanks for the comments. Very useful! We'll be reviewing them in the next weeks. 
Here are some quick comments about some of them:

1) I cannot replicate the issue. The home icon appears highlighted when loading the page. Can you provide the suffix of the URL when you see this behavior? (whatever is after yoursite.com/)

![ontask____workflows](https://user-images.githubusercontent.com/641160/53204261-16a06b00-367b-11e9-9cf6-c2571b7c8884.png)

2) The SQL connection menu is an ADMIN only feature. It is to manage (create, edit, delete) the connections with SQL databases. This is why it is available as the top menu, and why the links related to the workflow disappear. Regular users will not see this feature. Admin do. 

3) Agree!

4) Pondered over this for a bit. Icons only gives a very compact representation (suitable for mobiles) and follows a bit the trend you see in other platforms of hovering to find out what is that about. Gmail, for example, relies on this. One of the top menu bars has seven icons without titles. But we can change it to include the titles...

**Comment by abelardopardo** [comment]
Regarding 3) We are thinking to better place them only in the Login page (remove them from the Home Page)

**Comment by firasm** [comment]
1. hmm okay, it's like that the moment after I log in. I just noticed that 4.0.1 is the latest, we're still on 4.0 so it may have been fixed. Let's leave this until we upgrade next time.

2. Ah ok, that's perfect.

3. Login page only would be even better!

4. Normally I'd completely agree with you and the minimalistic approach. However in this case, there is not a logical/accepted 1:1 mapping between "Workflows" and "Home icon", "Actions" and "Chat bubbles icon", etc... 

Totally up to you, of course!

**Comment by abelardopardo** [comment]
1) There may be some conditions that need tyding up for the icon to be highlighted. Once you see it not highlighted, copy/paste the suffix of the URL

2) Actually, after reading a bit more in detail what you meant, I finally got it. You are right. It belongs to the right of the menu. I could even dissappear as the functionality is part of the admin sub-site, but we'll leave it for now.

4) Yes, I gave it another thought and you are right. I'll toy around and see if I can maintain a tight menu :)

Good comments, keep them comming!

**Comment by abelardopardo** [comment]
New menu bar

<img width="712" alt="ontask____table" src="https://user-images.githubusercontent.com/641160/53281623-931a7300-377b-11e9-9f8e-3a992df181ab.png">

**Comment by abelardopardo** [comment]
Found the glitch you reported in 1). Will be fixed in the next release.

**Comment by leichtweis** [comment]
> New menu bar
> 
> <img alt="ontask____table" width="712" src="https://user-images.githubusercontent.com/641160/53281623-931a7300-377b-11e9-9f8e-3a992df181ab.png">

nice solution, this menu change will be really helpful for the users.

**Comment by abelardopardo** [comment]
Fixed in release B.4.1
