### ISSUE TITLE
Messages in preview window do not wrap correctly

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#129]
Messages in preview window do not wrap correctly

Seems to happen universally.

<img width="1680" alt="wrap" src="https://user-images.githubusercontent.com/2507459/53141655-beb41800-3545-11e9-90bf-f3b3234f1c48.png">

**Comment by abelardopardo** [comment]
Would it be possible for you to "export" the action and provide the file? It will not contain any data. I just want to take a look at the HTML that is extracted from your editor screen.

**Comment by firasm** [comment]
Sure, here's an example. 
[ontask_action_190221_141915.zip](https://github.com/abelardopardo/ontask_b/files/2891524/ontask_action_190221_141915.zip)

**Comment by abelardopardo** [comment]
This behavior applies for Canvas actions. Looking into it.

**Comment by abelardopardo** [comment]
Fixed in release B.4.1
