### ISSUE TITLE
Message content length. 

### ISSUE THREAD

**Issue by scmc** [abelardopardo/ontask_b#13]
Hello,

I am not sure if this is a bug or a setting I missed. Is there a max content length for the email message body? They seemed to get trimmed around 2500 characters.

**Comment by abelardopardo** [comment]
We have reviewed the models in the tool and in principle, there is no restriction in the length of the message. They are properly stored, but we need a bit more testing on this to verify. We'll report on this shortly. Can you please add the version of OnTask you are using? 

Thanks!

**Comment by scmc** [comment]
We are using Version: B.2.3.1 

Sorry I did a very poor job of describing the issue.  

On the Actions edit_out  screen if you enter a large body of text and hit preview the pop up will not load and the text entered will be removed from the form text field content area. The content will be saved properly if you hit save first but you will not be able to preview the message.

**Comment by scmc** [comment]
should also note the send_email preview works with large text.

**Comment by abelardopardo** [comment]
Thanks for the extra information. 

We have pinpointed the issue. The fix is not trivial and may take a bit, but will be included in the next release. Stay tuned to this ticket.

**Comment by abelardopardo** [comment]
Fixed in version 2.5.1
