### ISSUE TITLE
Handling of whitespace and line breaks in conditions

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#135]
I would like to propose a change in how OnTask deals with whitespace with conditions. It might seem like a small thing, but when using multiple conditions, several instructors are quite put off by the un-intuitive formatting quirks. Here's feedback from one instructor:

> I think an improved interface could be helpful (especially for the conditional messages). I was unhappy with sending out things that had some odd spacing within (and I think it makes the messages look more like spam), but it was a bit too cumbersome to fix it all every time.

Here's an example that illustrates the point (from a different course). 

Ideally one would put each condition on a new line so the email template is readable and it's easier to troubleshoot. However, that line break persists even if that condition evaluates to NULL. The net result is weird spacing when the students get the messages.

<img width="1494" alt="screen shot 2019-03-08 at 2 23 23 am" src="https://user-images.githubusercontent.com/2507459/54023202-3474d200-4149-11e9-949d-53044766a792.png">

Here is the workaround I had to use:
<img width="1532" alt="screenshot" src="https://user-images.githubusercontent.com/2507459/54008052-b9e08e00-4119-11e9-9d27-e516107e9caf.png">

Note the giant block of text that is unreadable when the whitespace is removed. Note also that when I want line breaks, I have to put the line breaks INSIDE the condition (see Cond D1 and E1). I think colour will help for readability (#83) but I don't think it'll fix the underlying issue.

Potential fixes: 

- "skip the line" if condition does not evaluate to true
- Addition of another layer "above" text conditions so message crafting is easier
- Change WYSIWYG behaviour so the editor behaves more like a code-editor and all formatting, line and paragraph breaks happen inside the conditions [definitely not ideal]

To be fair, I haven't quite thought through the implications of this change (i.e. are there use cases where someone would actually take advantage of this feature?). Do you have other ideas on how to get around this issue?

**Comment by abelardopardo** [comment]
Good initial analysis. I have a couple of ideas but I need to test them. One of them is to consider the newline before and after a condition as part of the block to show/hide. This could probably solve most of the cases, although it will be a bit unpredictable in terms rendering when the condition is used in the middle of text. I'll try to work out some tests.

**Comment by abelardopardo** [comment]
@firasm Question. Is your analysis based on CANVAS emails? Or regular personalized text with HTML?

**Comment by firasm** [comment]
We’ve been using the canvas emails, haven’t tried with the personalized text yet!

**Comment by abelardopardo** [comment]
@firasm I just pushed a new commit (mind you though that it follows a few other additions) with a first implementation for the filter. Take a look and let me know if it helps.

**Comment by abelardopardo** [comment]
Included in release B.4.2
