### ISSUE TITLE
Wishlist: visualizations closer to where conditions are created

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#136]
I know that OnTask has pretty nifty visualizations in the Table page. Do you have a sense of whether users find them useful there? 

I wonder if they would be much more useful closer to where the visualizations are "actionable" ? For example, while the instructor was creating the text conditions, they could use the distributions to help guide their thresholds. 

<img width="920" alt="vis" src="https://user-images.githubusercontent.com/2507459/54009538-07f89000-4120-11e9-9982-74e33485b80d.png">

If this plot was close to where I was creating text conditions, I would be able to set conditions quite easily - rather than go back and forth from Excel to see which students would receive what.

Of course this naturally makes one think it would be useful to create conditions on individual columns visually using drag and drop - but that will be extremely involved and I'm not sure it'll be useful to everyone (perhaps only the OnTask novices).

Thoughts? Is there a way to visualize the column distribution while text conditions are being created?

Here might be a good place?

<img width="583" alt="screen shot 2019-03-07 at 9 33 17 pm" src="https://user-images.githubusercontent.com/2507459/54009728-cddbbe00-4120-11e9-9b0f-e285d3eef3d1.png">

**Comment by abelardopardo** [comment]
Good one! There are a few things that need to be worked out due to the use of an external library for those renderings, but this is something definitively worth considering. I like it!

**Comment by abelardopardo** [comment]
Pushed an initial proposal in B.4.2. Rather than allowing the visualization in the modal (small window that appears on top of the page when editing a condition), it is available at the "condition" tab in the action. Still much closer than going back to the Column operation page. Comments are welcome.
