### ISSUE TITLE
Wishlist: Flag to warn instructors about messages where no conditions evaluate to true

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#137]
When crafting messages in OnTask, one thing I tell all the instructors using it is that they should think about and consider edge cases carefully. 

A couple of times, they were able to catch messages that looked like:

> Dear Student name,
> 
> 
> 
> 
> Thanks,
> Jack

because some of the conditions weren't set correctly so all of them evaluated NULL for this student.

Can we think of ways to flag/surface odd looking messages for instructors to consider in an automated way? Perhaps something like "If the number of words in a message is less than 2 standard deviations away from the mean, ask the instructor to check Message 56, 89, and 42 using the preview screen".

Currently our solution is just to flick through all of them or spot check. I realize I may be asking for too much here, at some point instructors do have to take responsibility for the messages that are being sent on their behalf, whether or not it's machine-assisted!

**Comment by abelardopardo** [comment]
Detecting messages where all conditions are equal to False and flag them is simple. Let me explore this avenue first.

**Comment by abelardopardo** [comment]
Here is a compromise. We detect the rows in the table for which all the conditions evaluate to false. If there are any of them, there will be a warning band in the editor, the email send page, and the action will have an icon in the action page. How does this sound?

**Comment by abelardopardo** [comment]
Fixed in B.4.2
