### ISSUE TITLE
Release 4.1 ?

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#138]
Hi @abelardopardo - just quickly checking in to see if you'd consider the latest branch on master "release-worthy"? 

The changelog is at 4.1 https://github.com/abelardopardo/ontask_b/blob/master/ChangeLog.md

But the releases is still at 4.0.1.

No rush just thought I'd check to see as we're wanting to get to 4.1 with the interface tweaks.

**Comment by abelardopardo** [comment]
Hi @firasm. Sorry, yes, I forgot to push the new label (one git command missing). The label should now be pointing to the commit with id 994ce89e8
