### ISSUE TITLE
Missing data is handled differently by Filters and Conditions

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#14]
Filters and Conditions behave differently with missing data. This is unexpected. It seems to me that either both should handle missing data, or both should raise errors to the user when they encounter missing data.

Example: I have used "my_column >= 1" as a Filter, which drops rows with no value for 'my_column'. The same rule used as a Condition (again, with missing data) causes an error to be displayed in the preview window:

> This preview could not be produced because the row in the table does not have values in the 
> following variables:
> - my_column 
>
> Review the conditions in the action or use a filter to exclude these entries.

(OnTask Version B.2.3.1)

**Comment by abelardopardo** [comment]
Good catch! We have a few tests handling NoData. We will review them and see if we can make them a bit more coherent.

**Comment by abelardopardo** [comment]
An update on this issue. I pinpointed the problem. We are now considering the option of dropping entirely "integers" from the data types and handling only "numbers" as Pandas has some odd behaviour handling NaN and changing data types. We need a bit more time to sketch the correct solution. Hang in there.

**Comment by abelardopardo** [comment]
Fixed in release 2.5.1
