### ISSUE TITLE
image issue in OnTask email

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#140]
1. need to provide a new open access web server to serve these user uploaded images through summernote image plugin. as django server wont serve static files in production mode and these images also need to be open access for email clients to download.
2. the current EmailMultiAlternatives method in action/ops.py send_messages function, email message in outlook: text message will be display first and html message as attachment; gmail will display both messages with text message first and html message next.
Our academic wanted to send badge icons to students about their quiz result, so it's better to show image or html message directly 
I changed the EmailMultiAlternatives to attach html message first then text message.
maybe the original code could change to attach html email first and then attach text message as alternatives.
        ```
        message = MIMEMultipart()
        message["From"] = from_email
        message["To"] = msg_to
        message["Subject"] = Header( msg_subject ,'UTF-8' )
        message["Bcc"] = ",".join( bcc_email_list )
        message["Cc"] = ",".join( cc_email_list )
        # Add body to email
        message.attach(MIMEText(msg_body+track_str, "html", "utf-8"))
        message.attach(MIMEText(text_content, "plain", "utf-8"))
```

**Comment by abelardopardo** [comment]
I could not replicate this case. The emails sent to both Outlook and Gmail with the text + HTML attachment are rendered automatically in HTML. I've bubbled this issue all the way up to the configuration as the EMAIL_HTML_ONLY option. If true, only the HTML format of the message is included, otherwise, both HTML and text are included.

**Comment by abelardopardo** [comment]
Fixed in release B.4.3
