### ISSUE TITLE
Large messages in Action Out break interface

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#15]
Large messages (mine is more than 4000 characters) break features of the UI in the Action Out page. When the message is large, the 'Save' button works, but the 'Preview', '+Add Filter', and '+ New'(Condition) buttons cause the page to reload, rather than displaying their usual pop-up windows.

When I delete a significant portion of the message and re-save, the buttons regain their usual functionality.

(OnTask Version B.2.3.1)

**Comment by abelardopardo** [comment]
This is the same as reported in issue #13. We have identified the cause and we are working on the solution.
