### ISSUE TITLE
Unable to "Insert Column Value" into Personalized text or Canvas messages

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#150]
**Describe the bug**
'Insert column value' feature in OnTask v4.3.4 does not work for newly created workflows. It seems to work fine in older workflows (i.e. those created before 4.3.4).

**To Reproduce**
1. Create new workflow
2. Upload test dataset ([test1.csv.zip](https://github.com/abelardopardo/ontask_b/files/3142957/test1.csv.zip))
3. Create new action 
4. Try to insert column value

Alternatively, simply import the workflow attached here 
[ontask_workflow_190503_102844.gz](https://github.com/abelardopardo/ontask_b/files/3142963/ontask_workflow_190503_102844.gz)

**Expected behavior**
Dropdown of current col values.

**Screenshots**
![dropdown](https://user-images.githubusercontent.com/2507459/57155097-64c69e80-6d8f-11e9-96bf-3432b07671bc.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser Problem exists in Safari and Chrome (haven't tested others)

**Additional context**
FYI, this may be related to #149 but I do not have that or other extensions running.

**Comment by abelardopardo** [comment]
Working on replicability...

**Comment by abelardopardo** [comment]
Fixed in 4.3.5. Was able to replicate and add test case to regression. Demo servers updated.
