### ISSUE TITLE
5_1_4 Canvas Oauth token issues

### ISSUE THREAD

**Issue by andrew-gardener** [abelardopardo/ontask_b#151]
**Describe the bug**
I recently upgraded from `Version_4_3_5` to `Version_5_1_4` had ran into issues generating Canvas API tokens.

**To Reproduce**
1. Configure ontask with one entry in `CANVAS_INFO_DICT` (might be relevant for a second issue I ran into)
2. Attempt to send a new Canvas message

**Expected behavior**
A message is send

**Additional context**
I'll include a PR for review with a fix shortly (see #152)

**Comment by abelardopardo** [comment]
The error has been detected and fixed in the next release. Thanks for the fix and the PR.

**Comment by abelardopardo** [comment]
Release 5.2 fixed this issue
