### ISSUE TITLE
v5.14 schedule action for personalized_text not working

### ISSUE THREAD

**Issue by whol019** [abelardopardo/ontask_b#153]
v5.14
the celery log reported unregistered task of type 'ontask.tasks.execute_scheduled_actions'

change base.py 
CELERY_BEAT_SCHEDULE: ( I change it to the one below, then it works)
'task':'ontask.tasks.scheduled_actions.excute_scheduled_actions'

then in tasks/scheduled_actions.py
the send_email_messages() call -> only need 3 parameters but 11 parameters were passed 

Not quite know how to pass the action_info to the send_email_messages()

Thanks
Wen

**Comment by abelardopardo** [comment]
Release 5.2 fixed this issue

**Comment by whol019** [comment]
Sorry, this it not fixed yet.
in ontask/tasks/schedule_action.py, all these function calls the number of parameters provided did not match the required parameters for functions in send_email.py, send_json.py, and send_canvas_email.py

Wen
send_email_messages()
send_json_objects()
send_canvas_email_messages()

**Comment by whol019** [comment]
Below is my quick fix:
Thanks
Wen

1. in ontask/tasks/scheduled_actions.py, wrap the info into EmailPayload and replace the parameters for send_email_messages(), similar for two other action types 
2. in ontask/tasks/basic.py, mark out line 32, as the get_task_logger seems only need one parameter (https://docs.celeryproject.org/en/latest/_modules/celery/utils/log.html#get_task_logger )
#, extras={'lid':log_id} 

##########################
            action_info = EmailPayload({
                'action_id' : item.action.id ,
                'subject' : subject,
                'item_column' : item.item_column.name,
                'from_email' : from_email  ,
                'cc_email' : cc_email,
                'bcc_email': bcc_email,
                'action_id' : item.action.id  ,
                'send_confirmation' : send_confirmation,
                'track_read' : track_read
            } )
            

            result = send_email_messages(
                item.user.id,
                log_item.id,
                action_info )

            # result = send_email_messages(
            #     item.user.id,
            #     item.action.id,
            #     subject,
            #     item.item_column.name,
            #     from_email,
            #     cc_email,
            #     bcc_email,
            #     send_confirmation,
            #     track_read,
            #     item.exclude_values,
            #     log_item.id)

**Comment by abelardopardo** [comment]
Thanks. working on the merging.

**Comment by abelardopardo** [comment]
Fixed in V 5.2.2
