### ISSUE TITLE
Automatically assign users to Instructor group on LTI Launch

### ISSUE THREAD

**Issue by andrew-gardener** [abelardopardo/ontask_b#154]
**Is your feature request related to a problem? Please describe.**
Currently when launching via LTI users are authenticated (and new users are created if necessary) but instructors/admins/teaching assistants are not assigned into the Instructor group so they cannot start using OnTask immediately.

**Describe the solution you'd like**
I'd like the option to automatically allow some launches to insert users into the Instructor group based on LTI launch roles.

**Describe alternatives you've considered**
Manually assigning users to Instructor group

**Additional context**
I'll created a PR with my approach

**Comment by abelardopardo** [comment]
Release 5.2 fixed this issue
