### ISSUE TITLE
Insert Column Value menu extends off screen

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#159]
**Describe the bug**
When there are a large number of columns in the data table, the list of options for the "Insert Column Value" dropdown menu on the action editor page stretches up off the top of the screen.

**To Reproduce**
1. Choose a workflow with a large number of columns
2. Create a new action
3. On the action editor page, click on the "Insert Column Value" menu button
4. See error (screenshots below)

**Expected behavior**
All options from the "Insert Column Value" menu should appear to the user and be easily selectable without adjusting browser UI size. Perhaps the popup menu could be scrollable for long lists of options, rather than displaying all values at once?

**Screenshots**
(Screenshots from Safari)
The first column appears to be "sid"
![Screen Shot 2019-08-29 at 11 36 19 AM](https://user-images.githubusercontent.com/6002755/63967133-99064f00-ca51-11e9-863d-d8d0d5abf9d3.png)

However, scrolling up reveals "email" as a column, hidden underneath the navigation header. But, it's difficult to select due to the elastic scrolling behaviour.
![Screen Shot 2019-08-29 at 11 36 41 AM](https://user-images.githubusercontent.com/6002755/63967135-99064f00-ca51-11e9-8124-6c247989be5a.png)

(Screenshots from Chrome)
The elastic scrolling behaviour is slightly different in Chrome, and can't be used to peek at the top of the list.
![Screen Shot 2019-08-29 at 11 43 15 AM](https://user-images.githubusercontent.com/6002755/63967517-77f22e00-ca52-11e9-9918-6c1b9fb2d6a6.png)

A workaround in Chrome is to zoom out to reduce the size of all UI elements until the full menu appears:
![Screen Shot 2019-08-29 at 11 43 38 AM](https://user-images.githubusercontent.com/6002755/63967581-96582980-ca52-11e9-950a-6b95ab643d87.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome and Safari
 - Version Chrome 76.0.3809.100 and Safari 12.1.2

**Comment by abelardopardo** [comment]
Fixed in Version 6.0
