### ISSUE TITLE
Messages that fail to generate previews also cause "System Error"

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#16]
The following error message is generated when attempting to send emails when one (or more) of the messages also fails to generated a preview.

> System error
> Oops! The platform had an internal error. We are sorry. We hope to address this anomaly soon.

It would be nice if the error message were more specific. I was able to diagnose this by clicking through all of the previews, but had to click through N previews to find the one message that was not generating properly. In my case, the message failed to generate a preview because a condition was applied to a field that had missing data.

(OnTask Version B.2.3.1)

**Comment by abelardopardo** [comment]
Thank you for troubleshooting this. We clearly need a bit more robust processing of the templates in the presence of NAs. We will tighten this in the next release and include some additional test cases to make sure we don't regress. Stay tuned.

**Comment by abelardopardo** [comment]
We finally worked out the problem (it required a deep review of how empty values are handled in the DB. This fix will be in the next release.

**Comment by abelardopardo** [comment]
Fixed in version 2.5.1
