### ISSUE TITLE
Documentation bug - Config file location listed incorrectly.

### ISSUE THREAD

**Issue by firewuff** [abelardopardo/ontask_b#161]
The install documentation 2.6.1 list the location of the configuration files as "ontask/settings" (i.e. <app_base>/ontask/settings given the context of this usage elsewhere).   This appears to be actually in  "/settings".

**Comment by abelardopardo** [comment]
Oops! It is one of the changes in the latest version. Thought we had all these fixed in the documentation, but clearly not... Thanks!

**Comment by abelardopardo** [comment]
On second thought, I just saw the version you mentioned. 2.6.1. The config file needs to be in <app_base>/ontask/settings. In version 6.0 it needs to be in <app_base>/settings (assuming that app_base is the folder you get once you cloned the repo...

**Comment by firewuff** [comment]
@abelardopardo sorry that was section 2.6.1 of the documentation, not the version number.  The Ontask version is 6.0.1

**Comment by abelardopardo** [comment]
Ok, good catch.

**Comment by abelardopardo** [comment]
Fixed in release 6.1
