### ISSUE TITLE
Personalized Rubric

### ISSUE THREAD

**Issue by abelardopardo** [abelardopardo/ontask_b#164]
**Is your feature request related to a problem? Please describe.**
It would be good to use a rubric to generate personalized feedback.

**Describe the solution you'd like**
Add functionality to create a rubric selecting criteria and levels of attainment, but every cell would have two elements: the description and the personalized feedback text. The purpose of the second element is to give learners suggestions related to the level of attainment they obtained on that criteria. Once created, allow an email that contains the appropriate feedback messages as a list in an email in a similar structure as what it is allowed in the personalized text.

**Additional context**

Something like this

![rubric_edit_table_tab](https://user-images.githubusercontent.com/641160/65504920-36488c00-df07-11e9-8e6d-4fa4228433e1.png)

When redering the content for each student, it would look like...

![rubric_preview](https://user-images.githubusercontent.com/641160/65504960-524c2d80-df07-11e9-920c-0b1074a1696e.png)

**Comment by leichtweis** [comment]
this would be a very helpful addition and extension of functionality.

**Comment by abelardopardo** [comment]
Fixed in release 6.1
