### ISSUE TITLE
Symbols in condition name prevent conditional logic from working correctly

### ISSUE THREAD

**Issue by dfoung** [abelardopardo/ontask_b#168]
Hi, I am afraid this problem mentioned in issue #128 still exists.
![screenshots](https://user-images.githubusercontent.com/55891161/65989713-0a656300-e43f-11e9-9b7f-032ffbe6fb79.png)

As suggested, I wrote two independent conditions, identical formula, one with a symbol "q2>3" [i.e. with a ">" / Screenshot at a top left] and the other without a symbol "q2larger3" [i.e. Screenshot top-right], and use them to control text [Screenshot at bottom]. However, only yhe one without a symbol woks.

**Comment by abelardopardo** [comment]
Fixed in version 6.0.2
