### ISSUE TITLE
Admin UI: can't unshare Workflow

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#17]
Using the Admin UI "Change workflow" page, I have shared a user's workflow with myself, by moving myself from the "Shared"-> "Available shared" pane to the "Chosen shared" pane, and saving. This works.

I would now like to unshare this workflow with myself.

I have moved myself from the "Chosen shared" pane, to the "Available shared" pane. When I click "Save", I get the following error message at the top of the page:

> Please correct the error below.

and below the "Shared" panes, I see the following message:

> This field is required.

How do I unshare a user's workflow with myself?

(OnTask Version B.2.3.1)

**Comment by abelardopardo** [comment]
The Admin UI contains a full blown set of permissions in Django, but only a small subset is used by OnTask. If you want to share a workflow, that operation is done and implemented through the regular user interface (through the Share option in the workflow details page). My suggestion is that you use that UI. Use the admin UI only for very special tasks such as creating a new user.

Regards.

**Comment by craigdsthompson** [comment]
Hi @abelardopardo, I'd like to re-raise this issue. I'm finding a common pattern in how I support instructors to use OnTask is the following:

1. Instructors email me with a concern about a weird behaviour or issue they are having with their OnTask workflow.
2. I ask them to share the workflow with me so that I can investigate.
3. I edit (or clone and edit if I want to preserve the original) their workflow, until the original issue is resolved.

I've been through this process several times, and my "workflows" page is now cluttered with shared workflows from all the instructors I've helped to troubleshoot issues.

A minor request: I'd like to be able to remove myself from a workflow that has been shared with me (just to reduce the clutter in my workflow view).

A slightly larger request: most instructors assume that because I am providing support, I can already access their workflows. It's a bit tedious to have to ask them to share their workflow with me, after they've already asked for help troubleshooting. It would be nice if OnTask superuser or staff users could see other users workflows, or add themselves to the share list for a workflow. I've attempted to do that via the admin UI, but based on your comments (and my experience) that doesn't seem to be supported.

**Comment by leichtweis** [comment]
I concur, this would be helpful:

_A minor request: I'd like to be able to remove myself from a workflow that has been shared with me (just to reduce the clutter in my workflow view)._

**Comment by leichtweis** [comment]
_A slightly larger request: It would be nice if OnTask superuser or staff users could see other users workflows, or add themselves to the share list for a workflow._ 

I do this @craigdsthompson through the add workflow functions on the admin panel. You do need to know some details about the workflow (eg, id#, description, name, etc) in order to drill down to the correct workflow. This can involve a bit of sleuthing on oyur part if you have a lot of staff using the tool though.

**Comment by abelardopardo** [comment]
Thanks for bringing this issue again. I reviewed this problem and found a way to support it.

With the changes introduced, If you go to the same page in the Admin subsite, you'll see this:
![OnTask_Admin](https://user-images.githubusercontent.com/641160/64098227-78b5f780-cda5-11e9-8266-50dc25685501.png)

Selecting the user and using the arrows will then allow the share update as it was initially intended. The change will be included in the next release.

**Comment by abelardopardo** [comment]
The problem was with the definition of the fields. They needed some extra attributes to be manipulated appropriately through the Admin UI

**Comment by abelardopardo** [comment]
Fixed in Version 6.0
