### ISSUE TITLE
Column name has an effective max length that isn't enforced

### ISSUE THREAD

**Issue by damianfs** [abelardopardo/ontask_b#170]
**Describe the bug**
When creating a column it is possible to give it a name that is greater than 64 characters. However, when using a long column name in a personalised text action the data is not populated for that column (at least in the preview).

**To Reproduce**
1. Create a new workflow
2. Import a CSV with a column name with more than 64 characters
3. Confirm that the column is imported and contains data
4. Create a personalised text action
5. Add the column to the text using 'Insert Column Value'
6. Click preview to verify that the data is not shown.
7. Click more -> Manage columns
8. Rename the column using a shorter name (say fewer than 60 characters)
9. Repeat step 6 in the Action
10. Verify that the data is now displayed. 

**Expected behavior**
Column name should have a maximum character limit set in order to avoid confusion.

**Desktop**
 - OS: Debian
 - Browser: Firefox
 - Version: 60.9 ESR

**Additional context**
Using OnTask 6.0.1

**Comment by abelardopardo** [comment]
Problem found. Limit is imposed by underlying database (PostgresSQL). Considering solutions.

**Comment by abelardopardo** [comment]
Fixed in release 6.1
