### ISSUE TITLE
Enhancement to new "Send List" (or escalation) functionality from issue #158 

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#185]
**Describe the solution you'd like**
With the addition of the "Send List/Send List JSON" functionality identified in issue #158 (closed) it is now possible to send a list of students who are not engaging within a unit/course as an instructor expects. This has been a great addition because it allows teaching staff to escalate (or refer) identified students to specific staff or support groups within the university that are hired to assist students with the transition to HE, study skills, or other types of support that might be beyond the expected workload of an instructor. 

Currently, the "send list" function will create an email that might look something like this particular tongue-in-cheek example.
![OnTask escalate_ send list function](https://user-images.githubusercontent.com/14169588/74614641-76423100-517e-11ea-823f-99188890ad4e.png)

This is a good start but from the perspective of the student support staff that might receive this message, it requires a bit of effort on their part to convert a single column of comma-separated data (whether email address, student ID #, or Full Name, etc) to a useful list/spreadsheet containing all the key identifying details for each student (assuming that info is included in your workflows).

If it was possible to extend this current functionality so that key identifying columns of data were also included in an easy to use format, then the support groups that receive this escalation email should have all the information they need to act speedily. In the screenshot below (using the bogus data from the inbuilt OnTask scenarios) the email, ID and full name are provided in a list format. 
![Screen Shot 2020-02-14 at 5 32 51 PM](https://user-images.githubusercontent.com/14169588/74614819-3bd99380-5180-11ea-9df2-8437672ab0d5.png)

This particular "view" is possible within the Table Views option and that function under the Table submenu might be a useful way forward for this enhancement request.
![Screen Shot 2020-02-17 at 12 22 06 PM](https://user-images.githubusercontent.com/14169588/74614829-514ebd80-5180-11ea-8d35-998f49d401cc.png)

**Comment by abelardopardo** [comment]
Good suggestion!

**Comment by abelardopardo** [comment]
Here is a screen capture of the new preview

<img width="783" alt="OnTask____Edit_Action" src="https://user-images.githubusercontent.com/641160/80894773-6538a300-8d1d-11ea-8638-b88b5bf5f106.png">

**Comment by leichtweis** [comment]
Yes, that'll be a very useful upgrade to the formatting.
