### ISSUE TITLE
Fonts (Accessibility)

### ISSUE THREAD

**Issue by mylesblaney** [abelardopardo/ontask_b#188]
How to replicate: create an action page that doesn't include all users > save action > notice appears (e.g. 399 users have all conditions equal to FALSE) > error message is poor contrast.

**Comment by mylesblaney** [comment]
I have changed this to a general fonts issue:
All italics should be removed

Font on some pages is light grey on white (e.g. workflow operations > learners >  "Learners do not have access to the content in this workflow"

**Comment by abelardopardo** [comment]
Is this the error message you refer to? 

![OnTask____Edit_Action](https://user-images.githubusercontent.com/641160/79058890-a1df2480-7cb2-11ea-9828-947e6a00749f.png)

Is that message in "Italics"? It does not have any markup with that value. Is the issue the contrast?

**Comment by mylesblaney** [comment]
sorry for the confusion, the image is for poor colour contrast.
An example of italic fonts is when a new workflow is created with no data (image below)

![image](https://user-images.githubusercontent.com/5136408/79540273-ca369c80-807f-11ea-9cc8-a097a43fc23a.png)

**Comment by abelardopardo** [comment]
Removed italics
