### ISSUE TITLE
Screen Reader Jaws (Accessibility)

### ISSUE THREAD

**Issue by mylesblaney** [abelardopardo/ontask_b#190]
**Is JAWS Compatible with the application?**
JAWS is a software package that converts text to speech making it useful for blind and visually impaired users.

On the whole JAWS is compatible with the site to a certain degree. Jaws is able to read the text but some items have been incorrectly labelled (e.g. profile icon, manual icon).

This would make the system difficult and perhaps impossible to use but could easily be fixed.
When insert + F7 and F6 were used the system did recognise headings and links. The links could be better labelled to aid navigation so instead of on the home page three links sating “open” the link could say what they opened as many screen users will use links and headings to speed up navigation around a document.

**Comment by mylesblaney** [comment]
Plus can the manual and profile icons have tool tips enabled.

**Comment by mylesblaney** [comment]
Ensure the system is compatible with JAWS by ensuring all items are correctly labelled

**Comment by abelardopardo** [comment]
Could you point to those three links in the home page that state "open"? Are they those that open a workflow?

**Comment by mylesblaney** [comment]
The example given is for 3 shared workflows (the user had logged in already) thus the tester only had the 'open' option displayed in the workflow options.

**Comment by abelardopardo** [comment]
Some enhancements included to improve the usage of screen readers. Reopen if needed.
