### ISSUE TITLE
Log Search\Filter (DB Admin)

### ISSUE THREAD

**Issue by mylesblaney** [abelardopardo/ontask_b#196]
Feature request which we can manage in a pilot however as a wider service would be problematic for troubleshooting issues.

**Describe the solution you'd like**
Logs to be filtered or searched. 
Currently you need to scroll or find (crtl + F) to check if an email has been generated for a specific user (in a large cohort). A filter and search option for logs would help reduce the log clutter allowing admins to quickly check if an email was sent correctly, or check who was working on an action etc.
The filter could be applied to all column except payload which could have the search option.

**Describe alternatives you've considered**
Manually scrolling through logs to check (not great when 700 emails sent per course)

**Comment by abelardopardo** [comment]
This feature is easy to implement using the search_fields feature included in Django Admin. Will likely make it to the next release.

**Comment by abelardopardo** [comment]
Addressed in Version 7.2
