### ISSUE TITLE
Add view function

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#20]
The 'Add view' feature is accessed via the Add view button on the Table page. This uses a lightbox effect to pop up the 'Add view' panel. The problem is that the 'Add view' panel can be closed by clicking anywhere within the dark grey area outside the 'Add view' panel (not just via the close button at the top of the panel). Therefore, if the user has entered any details into the various form fields, then accidentally clicks the grey area outside the panel, the panel closes and they lose their work.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
