### ISSUE TITLE
Add view column picker

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#21]
The 'Add view' panel is displayed via the Add view button on the Table page. There is a 'Column' picker that represents a drop-down list of checkboxes. Unfortunately, on Chrome, Firefox, and Edge, the drop-down list appears on the right hand side of the screen. It should be pinned to the bottom edge of the drop-down list. I haven't tested it on Safari or Opera.

![capture](https://user-images.githubusercontent.com/20100002/39972516-d1d049d6-5765-11e8-8288-8e1afdabd4bf.PNG)

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1 (needs a bit more testing though)
