### ISSUE TITLE
Email Validator too strict?

### ISSUE THREAD

**Issue by firasm** [abelardopardo/ontask_b#216]
**Describe the bug**
Let's say I have a class list of 350 students, and I've got working, valid emails for 330 of them, and missing, empty, or incorrect emails for the remaining 20.

Several related issues arise from this:

- If my email column is not a "Key" column with unique entries (even if it contains multiple blanks, which makes it non-unique), I cannot select the email column in the "Send Personalized Text" action. 

- (I think) if ANY of the emails in my email column have typos in it, I will not be able to select the email column to execute the action.

- As a workaround, I created a "filter" and tried to only send emails to the 330 students. Nope, no cigar, all emails must be valid, even if not being sent via filter. 

- As another workaround, I decided to add unique "fake emails" for these 20 students so I could send the 330 emails and deal with the 20 later. No cigar. The emails have to be validated and real 

- OnTask does not tell me which emails are incorrect, I have to manually go through them one by one to figure out which ones aren't valid.

**Expected behavior**

I think there are several options:

1. Remove the requirement that the Email column be unique. 

This way, I can simply use "my email" for any blanks, so OnTask sends me the email that wasn't valid and I can follow up with the student outside of OnTask. 

2. Respect the "filter" setting

And only check/validate email correctness/uniqueness for emails *actually being sent*.

3. Substitute a default email (mine) for any that are incorrect.

4. Simply fail to send emails with invalid addresses (and tell the user which weren't successful). 

Overall, I think these changes would reduce some friction when you have a few bad apples in a class who can't/don't provide an email. You can't remove them from the class list because they're still enrolled, but you also shouldn't let this stop you from sending messages to the rest of the class while you sort this out. 

Thanks for the consideration!!

P.S. what finally worked for me is "alias emails" so adding an entry like: firstname.lastname+43@ubc.ca (and algorithmically generating the 43 uniquely for each student in python).

**Comment by abelardopardo** [comment]
Functionality added in version 10.3

**Comment by firasm** [comment]
Fantastic !! Great to see! I'll give it a shot when it's updated at UBC.
