### ISSUE TITLE
Table page - Active label

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#22]
The Table page has a green 'Active' label underneath the data type. What this is supposed to indicate? Can it be removed?

![capture](https://user-images.githubusercontent.com/20100002/39972626-877f1216-5767-11e8-9cf1-af7d98866613.PNG)

**Comment by abelardopardo** [comment]
Every column has a time-based "active" window. Two date/time elements can be defined per column to make it active/inactive. I suggest the wording to change to "Enabled/Disabled". Alternatively, only the "Disabled" columns may show a label. Any preference?

**Comment by clearnz** [comment]
Okay, Now I notice the date-time fields when I edit the column heading, and it shows Inactive when I set yesterday's date, though I still don't know what they do, so changing the names to Enabled/Disabled won't help. I agree though that you should only show the label if the column is inactive (or disabled) and perhaps have a tooltip on mouseover explaining the feature?

**Comment by abelardopardo** [comment]
Good point.

**Comment by abelardopardo** [comment]
"Active" message will not appear. Only "Disabled" if the column is disabled, and the popup will say "Out of given date/time window. Edit column to enable"

**Comment by clearnz** [comment]
Sounds good.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
