### ISSUE TITLE
Explaining filters and conditions

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#23]
This relates to the 'Action Out' feature. On-screen instructions have been added, since the last release, that helps users understand what is meant by filters and conditions. We're not sure if this goes far enough so we propose the following wording (the sentence "There are no conditions yet" doesn't add any thing to the UI, so it could be changed for an explanation):

![untitled-2](https://user-images.githubusercontent.com/20100002/39973048-5b03efa2-576e-11e8-8762-3ca2e6710a23.png)

**Comment by abelardopardo** [comment]
The word "conditional text" could be a bit misleading in the sense that what you "Add" is a condition, not the text. The text is added in the editor and then "surrounded" by the condition. This is the rationale behind "Text Conditions". 

The same applies to the second sentence suggested. The message should inform that conditions can be added, not text. The text for those who meet a condition is actually added in the editor below.

Thoughts?

**Comment by clearnz** [comment]
Okay that's true, strictly speaking, but "Text Conditions" still doesn't help first-time users understand what it does.

If I step back and think about what makes this feature different from 'Filter learners,' I realise that 'Filter learners' is one step - you set a filter and you don't have to do any more - whereas the 'Text Conditions' is two steps - you set the condition, then you have to click the drop-down on the text condition button that appears to insert it into the body of the email. This is where the UI lacks visual clues.

I can see that you've added a tooltip on the [+ New] button next to Text Conditions, great, but it's a missed opportunity to expand further on what the button does. Perhaps instead of stating the obvious (it currently says "Define a new text condition"), the tooltip should say "Define a text condition that can be inserted into the email." Then for the the tooltip that appears on the dropdown button (where you are inserting the condition syntax into the email), perhaps change the wording to "Insert text condition into the email body."

What do you think?

**Comment by abelardopardo** [comment]
Very good points. I specially like the distinction you pointed between filters and conditions. You are right. The filter is a one-off action and is already in use, whereas the condition needs an extra step. 

I am changing the tooltips as you require, but with one small change. The "text" in the body could be either part of an email or part of a personalised page that is served, so I'll replace the word "email" by "text", that way, the comment applies to both.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
