### ISSUE TITLE
Explaining Action In and Action Out

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#24]
When creating an Action, some participants of Abelardo's workshop didn't know what 'Action In' and 'Action Out' meant. There are tooltips, but the Action Out is still not self-explanatory. Consider changing the name to something like ‘Invite feedback (gather data)’ and ‘Send feedback (based on data)’

**Comment by abelardopardo** [comment]
Need to think about this a bit more. Feedback is much more than what the actions are suggesting. "Gather data" is easy. "Send feedback" assumes email, and feedback is much more than that. Perhaps "Create personalized content"?

**Comment by clearnz** [comment]
Okay, I thought feedback was just sending email. What else can Action Out do?

**Comment by abelardopardo** [comment]
It offers a personalised text to the learners. This is the distinction between "sending the emails" or making that page available to students. Think, for example, some badges. The page will personalise its content based on some rules that will be evaluated for each student separately, but it is not an email that is sent out. I struggle with the naming part in here. There is information going out, but the channel can be email or web. The essential part is that this information is personalised. With this in mind, names such as "Personalised Page", or "Personalised Text" could be an option that reflects more accurately what we are offering. Do you think these could work? I'm totally biased on this...

**Comment by abelardopardo** [comment]
How about:

- What it used to be "Action Out" will become "Personalized content"

- What it used to be "Action In" will become "Data capture"

**Comment by clearnz** [comment]
Sounds good.

**Comment by abelardopardo** [comment]
Here is another proposal: 

* Action Out: Personalised Email

* Action In: Survey

This, togeher with a suggestion to fold the two buttons to create Action In and Action Out into a single one that asks for the name and description and a pull down menu to choose which one. This would then open the platform to include additional ones.

**Comment by leichtweis** [comment]
Yes, like it. Along with the proposed idea for a rejigged "create a new action" pop up box that Richard identified. This process would become more intuitive with expansion potential.

**Comment by abelardopardo** [comment]
See #77
