### ISSUE TITLE
Rich text editor drag event

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#25]
Traditional  rich text editors allow you to highlight some text within the editor and drag it to another part of the body text. But when editing the email for the 'Action Out' feature, selecting some text and dragging it causes the editor to show an overlay saying "Drop image or text." If you then let the mouse button go (drop event) it will duplicate the selected text to where your cursor was. This is annoying, especially when you are trying to move around some of the 'text conditions' tags to different parts of the email body.

Suggest disabling the overlay because it doesn't work for dropping images onto it anyway.

![capture](https://user-images.githubusercontent.com/20100002/39973353-f5348178-5772-11e8-9fd1-b3b0d888620e.PNG)

**Comment by abelardopardo** [comment]
Fixed in version B.2.8.0
