### ISSUE TITLE
Text conditions doesn't show number of matches

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#26]
When  creating an email (Action Out) and applying a filter, you can see how many learners match the filter when the filter is applied. It would be good to have similar functionality to the 'Text Conditions' feature as well so you can see the number of students who match each condition.

**Comment by abelardopardo** [comment]
Here is an initial proposal:

![ontask____edit_action_out](https://user-images.githubusercontent.com/641160/40103200-cc71d65e-592b-11e8-8611-6ea54dbe1697.png)

Now, both filters and conditions show the number of rows that match the formula. If the filter is modified, all numbers are re-calculated. The number in the text condition is over those selected by the filter. The information also appears in the popup.

What do you think?

**Comment by clearnz** [comment]
Looks great!

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
