### ISSUE TITLE
Action In - Submit button vs Back button

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#27]
The 'Action In' survey has a Submit button but the next page shows a Back button. This encourages students to go back to the survey question(s) again. I understand that users might change their mind about their submission choices but this shouldn't be foremost on the 'submission successful' page. Maybe remove the Back button and place an instruction saying if they want to change their submission, just follow the link from the email again.

**Comment by abelardopardo** [comment]
How about a "switch" in the action to control the presence/absence of such button?

**Comment by clearnz** [comment]
Nah, don't clutter the UI with options that the user won't understand.

People love clicking buttons, especially when they're the only colourful thing on a page. I've never seen a submission confirmation page with a Back button before and it will only encourage students to click it, then see the survey again and wonder whether their submission worked or not.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
