### ISSUE TITLE
typos in v2.6 Workflow Details page

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#29]
Potential 'point of reference' confusion for users. The columns of data in the OnTask Table page are represented as rows in the Workflow Details page. The arrow buttons (green circle) allowing chosen columns to be moved to the left or right in the Table View are identified as moving columns 'up' or 'down' & 'top' or 'button' [sic] _- should be 'bottom_.'  Change for consistency.

![workflow details v2 6](https://user-images.githubusercontent.com/14169588/39973881-c751c062-5778-11e8-98b0-778cd25ffd84.png)

suggested mouse over directions:
^ = move one column left in Table View
v = move one column right in Table View
^^ = move to first column (far left) in Table View
vv = move to last column (far right) in Table View

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
