### ISSUE TITLE
Session timeout - no warning

### ISSUE THREAD

**Issue by clearnz** [abelardopardo/ontask_b#31]
As expected, the session times out due to inactivity - not traversing pages nor initiating Ajax requests - but there is no warning. When the user finally interacts with the website after their session has timed out, they are prompted to log in again. This is especially inconvenient if they had taken some time to draft an (Action Out) email, and they finally clicked 'Done', only to discover that their work was lost.

Propose adding a session timeout warning message that either prompts the user to save their work or keep their session active (the latter could just ping the server through an Ajax request).

**Comment by abelardopardo** [comment]
Solution included in next release.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
