### ISSUE TITLE
Track email reading without adding column

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#35]
Why are there two different checkboxes for tracking email reading?

When would/should a user track reading, but not add a column (the configuration selected below)?

The action-out [docs](http://ontask-version-b.readthedocs.io/en/latest/Using/actions.html#actions-out ) provide extra detail about the purpose of the _summary_ and _snapshot_ checkboxes, but not the two tracking ones.

![screen shot 2018-05-16 at 9 38 40 am](https://user-images.githubusercontent.com/6002755/40130805-f9fa1918-58ec-11e8-8ab2-330b11807ab1.png)

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
