### ISSUE TITLE
Workflow exports don't have descriptive names

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#36]
Exported workflows are all called ontask_workflow.gz

It would be helpful if the filename was more descriptive. Perhaps include the name of the workflow and the timestamp of when the export was generated?

**Comment by abelardopardo** [comment]
Good point. Opening this flexibility is a bit risky due to the variety of characters that could be included in the file name, but we will certainly explore.

**Comment by abelardopardo** [comment]
Next release will include at the end of the file the date/time such as 

ontask_workflow_180522_030509.gz

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
