### ISSUE TITLE
upload Excel file: default sheet name is incorrect

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#38]
When uploading an Excel file, the sheet name field is pre-populated with "Sheet 1". The default sheet name in Excel (for Mac v. 16.12) is "Sheet1". The subtle difference results in failure to upload the file.

Some solutions:

- leave the sheet field blank for the user to fill in
- pre-populate with "Sheet1" instead
- populate with the name of the first sheet in the workbook (after the user selects the file)
- populate a dropdown list of the sheet names in the workbook (after the user selects the file)

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
