### ISSUE TITLE
System error when merging multiple files

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#40]
While #39 alone is fairly innocuous, it leads to a more significant issue when merging multiple files:

1. I start with a "base" dataset of `name`s, `email address`es, and `SIS ID`s.
2. I merge a dataset of quiz 1 problem scores, keyed by `Student ID` (q1p1, q1p2, q1p3,...,q1p20). I do this merge on `SIS ID` from my Existing Table, and `Student ID` in my New Table.
3. I merge a second set of quiz 2 problem scores, again keyed by `Student ID` (q2p1, q2p2, q2p3,...,q2p20). Again, I do this merge on `SIS ID` from my Existing Table, and `Student ID` in my New Table. This merge results in a "System Error" and the merge fails.

**Comment by abelardopardo** [comment]
I am unable to replicate with the given instructions. Any chance to share the files that produced the error with me?

**Comment by craigdsthompson** [comment]
A small dataset to reproduce is attached.

Specific steps to reproduce (using version B2.6.0):

1. upload `roster.csv`
   1. load all columns
2. upload `A1.csv`
   1. load all columns
   2. key on `sis id` in existing table
   3. key on `student id` in new table
   4. select merge method 1 (all rows in both)
3. upload `A2.csv`
   1. load all columns
   2. key on `sis id` in existing table
   3. key on `student id` in new table
   4. select merge method 1 (all rows in both)

[issue40.zip](https://github.com/abelardopardo/ontask_b/files/2013979/issue40.zip)

**Comment by abelardopardo** [comment]
Excellent. The files replicate perfectly the anomaly. It is a corner case not considered in the algorithm (a column in the new table matches a key in the existing table and also has the same name of a column already existing in the table but not used as key).

The merge/update algorithm has now been updated and the new version will be included in the next release.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
