### ISSUE TITLE
Canvas 'time and date' data imported into OnTask 

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#42]
Experiencing the addition of an unexpected character into columns of 'time and date' data pulled from Canvas and imported into OnTask. We use a bespoke javascript tool to grab course data in CSV format from courses in Canvas that we then import into OnTask. The format for time and date appears fairly standard when viewed in excel 

![screen shot 2018-05-18 at 5 27 31 pm](https://user-images.githubusercontent.com/14169588/40217687-2b94465c-5ac2-11e8-9307-36bf8ea9fd25.png)

and within a text editor programme 

![screen shot 2018-05-18 at 5 29 04 pm](https://user-images.githubusercontent.com/14169588/40217691-35da8b62-5ac2-11e8-9162-5d215f59ea24.png)

But after getting imported into OnTask, a 'T' is introduced where a space is expected 

![screen shot 2018-05-18 at 5 27 53 pm](https://user-images.githubusercontent.com/14169588/40217710-598cfe1e-5ac2-11e8-8b95-aff5e919bca8.png)

I can send an example dataset for testing.

**Comment by abelardopardo** [comment]
This is just the internal representation of the date/time in OnTask. The T is not actually introduced, it is just the format chosen to show date and time.

**Comment by abelardopardo** [comment]
Solved in Version 2.6.1
