### ISSUE TITLE
Migrations are not properly executed due to lack of "future" package

### ISSUE THREAD

**Issue by abelardopardo** [abelardopardo/ontask_b#50]

**Comment by radhikavm** [comment]
Hi Abelardo, 
Had this issue when I were trying to upgraded this morning, found that  running pip install -r without sudo -H worked and installed all the required modules. future package already is a part of the [requirements.txt](https://github.com/abelardopardo/ontask_b/blob/716e4d3058017647a4c4a6ac3e13110dbc12b358/requirements/base.txt#L17)

**Comment by abelardopardo** [comment]
No fix needed.
