### ISSUE TITLE
session log out after unexpected disruption

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#52]
I experienced a web browser crash which did not automatically close my active OnTask session. When I re-engaged with the OnTask service I received a "competing session" error message - 
![screen shot 2018-06-29 at 11 21 11 am](https://user-images.githubusercontent.com/14169588/42070982-fa694378-7bac-11e8-9045-8a3e471f6de5.png)

After attempting to log out via the 'log out' button 
![screen shot 2018-06-29 at 11 42 32 am](https://user-images.githubusercontent.com/14169588/42071045-4529f65a-7bad-11e8-961c-e97b30457bdb.png)
there was no message indicating that this action was successful and I was returned to the OnTask information page. 
![screen shot 2018-06-29 at 11 42 41 am](https://user-images.githubusercontent.com/14169588/42071342-e304a658-7bae-11e8-9ef0-fad098784e9a.png)
My previous session remained active and I got the 'another session' error multiple times. Is this a server setting that we need to set correctly on our local instance or is this something that could be tweaked in the code for the 'log out' function in a future version. It is possible that inadvertently closing a web browser tab could result in a similar outcome.

**Comment by abelardopardo** [comment]
The login/logout is tied to the browser session (for security reasons) and it has a time out of 30 mins. If your browser crashes, the next execution will appear to the server as another "you" trying to access the same workflow and it is not allowed. After 30 mins, the old session expires and any other new session can then access the workflow. 

One way to adjust this is to change the session timeout (server configuration).
