### ISSUE TITLE
workflow data flush does not remove search bar content

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#59]
the workflow 'data flush' indicates that all info except name, description and action out text will get removed. We found that text in the search bar also remains post flush of the data set. I don't suppose that was intended.
[step 1 - search bar term in table.pdf](https://github.com/abelardopardo/ontask_b/files/2222169/step.1.-.search.bar.term.in.table.pdf)
flush of data as indicated
[step 2 - flush dataset in workflow.pdf](https://github.com/abelardopardo/ontask_b/files/2222175/step.2.-.flush.dataset.in.workflow.pdf)
upload new(same) dataset
[step 3 - upload new dataset in same workflow.pdf](https://github.com/abelardopardo/ontask_b/files/2222180/step.3.-.upload.new.dataset.in.same.workflow.pdf)
view of the new table is limited by the text entered prior to the data flush function
[step 4 - search term persists after flush.pdf](https://github.com/abelardopardo/ontask_b/files/2222186/step.4.-.search.term.persists.after.flush.pdf)

**Comment by leichtweis** [comment]
Also, found that the search tool is case sensitive which may be too exacting during normal academic use of the tool.

**Comment by abelardopardo** [comment]
Exploring how to remove this information after flushing the workflow. Not trivial. The memory is handled through in-browser database. Not trivial toflush that information. Need to explore a bit further.

**Comment by abelardopardo** [comment]
Fixed in version 6.1
