### ISSUE TITLE
option to filter for empty data cells

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#60]
The data sets we are pulling from Canvas LMS can contain empty cells which we would like to be able to search for.  Is there an opportunity to include 'empty' in the filtering terms?
![option to filter empty data cells](https://user-images.githubusercontent.com/14169588/43120478-6eaef6cc-8f6e-11e8-94dd-ff30c53f71bf.png)

**Comment by leichtweis** [comment]
here is a screenshot of those additional search options in the java version of SRES.
![screen shot 2018-07-31 at 12 13 58 pm](https://user-images.githubusercontent.com/14169588/43434335-510c47b2-94cf-11e8-9ba3-73dccf16b9f3.png)

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0
