### ISSUE TITLE
ability to override unique id column identification in dataset merges

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#61]
We've found that merging a new dataset with an existing workflow dataset doesn't provide options to manually set unique ID columns if they are not correctly identified during the merge upload process.
![screen shot 2018-07-24 at 6 41 56 pm](https://user-images.githubusercontent.com/14169588/43121618-757947ec-8f72-11e8-9e9d-a31bdfe3c7f6.png)

in our example, the existing workflow table contains username, ID number and email address correctly defined as unique but in the dataset that we wanted to merge from a different tool the 'username' column was not identified as a unique ID and we could not override that automated selection manually. A double checked of the dataset confirmed there were no duplicates in the username column being merged.

**Comment by abelardopardo** [comment]
Is it possible to take a look at the dataset? The check for unique is done by Pandas and is fairly reliable. I wonder if you have any "empty" row, or anything similar. It may be a corner case we didn't checked. DM me with the dataset of feasible...

**Comment by leichtweis** [comment]
so the two datasets are pulled from Canvas' production site. The first dataset is course click data and the second dataset is the course grade book data. They have to be gathered separately. The course click data has a single row acting as the header
![screen shot 2018-07-24 at 7 41 00 pm](https://user-images.githubusercontent.com/14169588/43124724-1265c130-8f7c-11e8-8185-2374a35570f9.png)

whereas the gradebook dataset actually uses two rows for its header information. 
![screen shot 2018-07-24 at 7 40 00 pm](https://user-images.githubusercontent.com/14169588/43124749-2a14b3ae-8f7c-11e8-884b-97c4dc7fb89b.png)

when I delete that second row (which contains marks available for the assignments identified in columns) the tool behaves properly.

**Comment by abelardopardo** [comment]
Yes, that makes perfect sense. That line in between contains a blank cell for the columns that typically have unique values (ID, SIS User ID, username, I'm guessing). These cells break the "unique" property. 
I am assuming then that this is the expected behaviour and I am closing this issue.
