### ISSUE TITLE
query about need for case sensitive search in 'action out' filter

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#62]
based on observations of a user, I wondered whether the case-sensitive requirement in the 'action out' filter was required? this example involves a subset based on the first letter of last name. 
![is case sensitive search function necessary](https://user-images.githubusercontent.com/14169588/43122999-fe568a44-8f76-11e8-9089-bef9cd9f0f75.png)
with the resulting search outcome identifying no users despite many having surnames which started with 's'.
![dataset contains individuals with surname starting with s](https://user-images.githubusercontent.com/14169588/43123111-4afebec0-8f77-11e8-8d68-5b9e40893202.png)

So, do we need to change our behaviour at this end or is a case-sensitive search requirement needed?

**Comment by abelardopardo** [comment]
Case sensitivity allows for more functionality. Case unsensitivity is allowed by using two clauses in the formula (begins with 's' and begins with 'S'). 

However, if made case insensitive, there is no way to distinguish should the need arise.

I think it would be better not to restrict functionality here.
