### ISSUE TITLE
text formatting issues when pasting from MSWord, Google Doc, or Google Sheet

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#63]
Copy/pasting text from another application that supports formatted text often includes a lot of junk (unintended) formatting.

Where possible, we've advised users to either write their feedback directly in OnTask, or if they must use Word or another platform they should "paste without formatting" or copy paste through a plain text editor as an intermediate step to strip formatting.

But, both of the above are extra work on the end user, and more importantly, the inconsistencies are not obvious to the user.

As a particular example of this problem, see the included screenshots. Portions of this text were copy/pasted from both a Google Doc and a Google Sheet, as well as entered directly into OnTask. The text appears totally 'normal' (no obvious formatting inconsistencies) in both the rich text editor, and the preview. But, both the HTML view and the rendered message sent to the student contain inconsistencies in the formatting. Note the email sent back from the student contains obvious inconsistencies in text colour and font size.

 Is there a way this can be improved within OnTask?

![rich_text_view](https://user-images.githubusercontent.com/6002755/43231729-692019de-9022-11e8-8bcc-089d1b388edd.png)
![rendered_preview](https://user-images.githubusercontent.com/6002755/43231745-779c05d6-9022-11e8-971c-8b6d47748c03.png)
![code_view](https://user-images.githubusercontent.com/6002755/43231755-7e44259e-9022-11e8-9092-7bcf0b33f5f9.png)
![rendered_email](https://user-images.githubusercontent.com/6002755/43231761-85d12a50-9022-11e8-8510-f3058f1db34d.png)

**Comment by abelardopardo** [comment]
We've detected this issue in the past and we have included some simple minimal steps when processing the template to try to avoid them, but as you mentioned, the type of code that can be embedded is highly unpredictable. An alternative could be to run some filters and warn the user to clean the text using some suggestions. Any ideas on this space  would be great.

**Comment by abelardopardo** [comment]
A first filter has been included in release 2.8. It does not clean the differences in fonts (that is easy to do simpliy by pasting without the format). Instead, it removes undesired new-lines in the content that break the template mechanism.

**Comment by abelardopardo** [comment]
Partially addressed in version B.2.8.0

**Comment by abelardopardo** [comment]
Fully addressed in next release!

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0
