### ISSUE TITLE
preview screen information

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#64]
Not sure if this particular info was alluded to in your issue #47 but it would be great if the email preview pop out box could also identify the total number of emails to be sent in an "Action Out"
![preview screen information](https://user-images.githubusercontent.com/14169588/43298943-6585dba2-91ac-11e8-8c81-d9e15965122b.png)

**Comment by abelardopardo** [comment]
Fixed in version B.2.8.0
