### ISSUE TITLE
email preview screen and ability to remove particular people from 'action out' messages

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#66]
Feedback from a staff user regarding greater manual control of the list of individuals to receive 'action out messages. In the filtering of a table, we identified 20 students that meet the filter conditions for this particular course but one of the students in that list had been contacted Face-to-face by the instructor already. There is no easy way for a user to remove this student without potentially exploring a complex set of filtering rules (which still might not work). In SRES v2 there was functionality to allow staff to remove specific students from receiving the communication even though they met the filter criteria.
![screen shot 2018-07-31 at 12 19 24 pm](https://user-images.githubusercontent.com/14169588/43430649-104d9214-94be-11e8-8656-249447c7566a.png)
![screen shot 2018-07-31 at 12 19 37 pm](https://user-images.githubusercontent.com/14169588/43430651-13147968-94be-11e8-825c-c03862c1e65f.png)

Possible that this could be an added function in OnTask email preview pane (probably more intuitive placement for this functionality) or in the subsequent send email page. Retaining information about all the filtered students in the summary/snapshot info for the 'action out' and whether they had been removed from receiving that message would be important info.
![screen shot 2018-07-31 at 12 10 40 pm](https://user-images.githubusercontent.com/14169588/43430859-2ff437ca-94bf-11e8-96f4-442a4ec3f960.png)

**Comment by abelardopardo** [comment]
Hi. I need to think a bit more where would it be the best place to put this information. In principle it would be simpler in the "Email page" rather than in the preview. Also, what happens if there are thousands of students? This information needs to be "sent" to the browser... 

I think I can come up with a first cut at it and circulate by you for feedback. It won't make it in the next release though. I'm packing a few things and need time for testing.

**Comment by abelardopardo** [comment]
The alternative that I propose is:

1) Maintain the page to send email exactly as is and let the user select the column containing the email.

2) Create a new page that informs the user about the emails that are about to be sent and asks for a final manual email filtering. The user may choose to filter some emails, or just proceed and the emails are sent.

It adds an additional step to the procedure, but I think it make sense to provide this "final summary before pushing the button" type of page.

Thoughts? @leichtweis

**Comment by leichtweis** [comment]
I am assuming you mean this page (attached) and the green "send" button leads to a new page containing the 'advanced' feature to manually override the results of a filter? That would work. Having a search capability on that new page so the user can quickly find someone based on unique identifiers would also be helpful.

![screen shot 2018-08-06 at 2 17 55 pm](https://user-images.githubusercontent.com/14169588/43693871-995b9798-9984-11e8-925a-a77c6bccf017.png)

**Comment by abelardopardo** [comment]
Great feedback. Here is the functionality as it is being included in the next release: 

First screen:

<img width="961" alt="ontask____email_action" src="https://user-images.githubusercontent.com/641160/44616915-6f43a680-a898-11e8-906c-b457602757cf.png">

Following screen (only if the option is selected)

<img width="1048" alt="ontask____exclude_emails_from_action" src="https://user-images.githubusercontent.com/641160/44616918-85516700-a898-11e8-8246-d3036c0b1046.png">

And yes, the widget allows "search as you type". To avoid potentially showing thousands of emails, the form is framed as asking for those "emails to exclude".

This functionality is also available when scheduling an action.

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0
