### ISSUE TITLE
Data uploaded lost

### ISSUE THREAD

**Issue by radhikavm** [abelardopardo/ontask_b#67]
Hi Abelardo,

We tend to loose the complete data table after sending out emails (approx. 500) though the emails have been delivered successfully. I have gone through the logs but they don't seem to show anything helpful about data loss. Any ideas why this could be happening?

**Comment by abelardopardo** [comment]
Managed to identify the cause of the bug and including the fix in next release.

**Comment by abelardopardo** [comment]
Fixed in version B.2.8.0
