### ISSUE TITLE
Sending large batches of emails with OnTask 

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#69]
Our ITS security team has email restrictions designed to limit/prevent spamming from staff email accounts. For tools like OnTask, we can request increases to the hourly email sending quota and whitelist the IP address for any server's that send large volumes of messages. In addition, we also have email filters that look for spamming behaviour and can blacklist individual accounts that are behaving in 'spammy' ways. It's easy to add OnTask to our internal whitelist of approved services so it doesn't go on the blacklist.

However, apparently, Google email (which is our student email service) also has a filtering system at their end that looks for 'spamming' behaviour and automatically blacklists or filters messages as they get delivered to a student's email account. An automatic blacklisting means OnTask messages could be dropped into their spam folders (reducing the likelihood they'd ever see them). One of the suggestions from our ITS team was to programmatically batch ONTask's sent emails so no more than 999 are sent at any one time to also ensure they fly under Google's spam filter radars. I am wondering whether you had considered a batch processing function as an automatic function in OnTask for very large courses?

**Comment by abelardopardo** [comment]
Identified a possible solution fairly reasonable to implement. Considering it for the next release.

**Comment by abelardopardo** [comment]
Issue fixed in release 4.0
