### ISSUE TITLE
juggling 'completed' actions

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#71]
An enhancement request from an academic piloting the tool. 
Introduce a column in the "actions' table to identify/show which actions have been executed / completed. At present this is dependent on the user having remembered to download / send a confirmation email to themselves, and cross-referencing the email notification with the dashboard.

![image001 2](https://user-images.githubusercontent.com/14169588/44014100-f575ab56-9f1d-11e8-9634-efc23f079754.png)

**Comment by abelardopardo** [comment]
This is comming in the next release. There is an extra column, as you suggested, with a link to the Log record documenting that execution. Here is the screen capture:

<img width="1144" alt="ontask____actions" src="https://user-images.githubusercontent.com/641160/44616850-13c4e900-a897-11e8-8b18-bd6cac7a389c.png">

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0
