### ISSUE TITLE
high level UX considerations

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#72]
In anticipation of our UX report, which highlights only high-level considerations for future OnTask improvements, I have developed some design suggestions for OnTask's top menu and the 'workflows' submenu. The UX report is still a work in progress but should available soon. The UX review was completed on v2.7.0 and a few of the recommendations from that may have already be addressed in v2.8.1+

1. Proposed top-level menu when first accessing the tool:
![proposed home page](https://user-images.githubusercontent.com/14169588/44014307-5556d92c-9f1f-11e8-9e1a-8f56aae8fab0.png)
The question as to whether the content of this landing page is needed is a question to consider as it competes with the home page for top-level status. Further, the information contained on the current landing page would usually be reserved for a signup or login page (ie. at the beginning of a sales funnel). As is, this page of content provides no call to action or suggest the next course of action for the user. Regardless of your decision for the content on this landing page, the top menu can be simplified (as indicated in the annotated screenshot) with only the 'home' icon on the LH side and a 'hamburger icon on the RH side providing access to a number of the overlapping functions and providing the potential to be extended with additional submenu items in the future. Clicking on the home icon on the LH side takes the user to the Workflows "Library" page discussed in item 2 (below).

2. The top-level menu in Workflows "Library" page
![proposed top-level workflows library page](https://user-images.githubusercontent.com/14169588/44014716-611837ae-9f21-11e8-9eaf-e26edeb7f0a3.png)
The Workflows 'Library' page can become more intuitive with the left justification* of information which in turn provides an opportunity to include additional content that educates/reminds users how 'workflows' work within the OnTask tool (which supports the call to action/sales funnel experience from the home page and supports intuitive use). From here, a user selects the workflow for interrogation (in this example - arts dataset test)

3. In the existing submenu in OnTask there is neither a hierarchical order nor intuitive experience for the user as a submenu is overlaid on the top-level menu (as below).
![current submenu](https://user-images.githubusercontent.com/14169588/44015052-310b856e-9f23-11e8-9d78-47e153c6458e.png)
It would be helpful and more intuitive to set and enforce the hierarchy of the 'workflow title' ahead of the actual submenu functions available when working with a workflow dataset 
![proposed submenu gui](https://user-images.githubusercontent.com/14169588/44015138-af01da22-9f23-11e8-91a5-0c7a0e224bc3.png)
by introducing a "steps progress bar" design into the submenu there are now stronger clues to (new) users about the linear sequence of events expected (even if some of these functions - eg, dataops & table become less relevant after a new workflow has been created). Highlighting/shading of the selected submenu item re-inforces the sequence expected as well as the current location for the user.
 
*left justification of page content will, in most instances, improve user experience - this issue is most obvious in the current Actions page.

**Comment by abelardopardo** [comment]
The sequence of steps in the top bar is intuitive, however, it may be confusing when presenting how the tool works. Those steps are only followed in such sequence in a very prescriptive type of situation. I can see how users can skipe the details, o to uploading data (which is ont in the menu), and then go straight to the actions. The table could become handy later once the data needs to be visualised. Also, there is quite a lot of space that is wasted in the top bar that pushes the content to the bottom of the screen increasing the probability of singificant scroll (not much as the bar is reduced. I think we could find a tradeoff by including the workflow name at the top and the menu immediately underneath in a shape that is similar to the current one. This would be a blend of the two ideas: maintain a compact representation but maintaining the flexibility in the steps.

I wonder if anybody else would like to chip in the discussion.

**Comment by abelardopardo** [comment]
New batch of changes in next release. Included most of the suggestions. The transformation of the menu into a set of arrows is still not there.

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0 Reopen of needed.
