### ISSUE TITLE
"notify selected users" function in admin console

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#75]
would this be a possibility? would make the process of identifying changes to actual users much quicker.
![screen shot 2018-08-15 at 9 29 16 am](https://user-images.githubusercontent.com/14169588/44130241-a0b7ecbc-a0a0-11e8-8c75-bdd6317891e7.png)

**Comment by leichtweis** [comment]
notify = email. but if it is not trivial then don’t worry

**Comment by abelardopardo** [comment]
From the admin page it is not trivial. Given the functionality of the platform, I'm guessing it would be simpler to create a workflow with their emails and notify them with a regular email action...
