### ISSUE TITLE
Proposal to send messages via Canvas Conversations (Canvas inbox)

### ISSUE THREAD

**Issue by craigdsthompson** [abelardopardo/ontask_b#78]
This is a sketch of a solution to send messages using the [Canvas Conversations API](https://canvas.instructure.com/doc/api/conversations.html).

* We should use [OAuth2](https://canvas.instructure.com/doc/api/file.oauth.html) to authenticate users between OnTask and Canvas.

* We should have a "Canvas Message" button beside "Email" under "Operations" on the Actions page. 

* There should be a "Schedule a Canvas message" under the "More" button on the Actions page.

* To limit UI complexity growth, the proposed "Canvas Message" button and "Schedule a Canvas message" drop-down should be enabled/disabled via configuration during the OnTask deployment. The same option could be added to the current "email" button. Likewise for other future messaging platform integrations.

OAuth2 details:

* We should store the user's Canvas API access_token and refresh_token within OnTask, both of which will be obtained via OAuth2. This will allow the user to authenticate with Canvas once, and for OnTask to avoid re-prompting the user for Canvas authentication details in the future.
* The OnTask user profile page should indicate if a Canvas API token is associated with the user, and include an option to delete the Canvas API tokens associated with the user.

When the user clicks the "Canvas Message" button:

1. If OnTask doesn't have a Canvas token for this OnTask user:
    1. initiate the OAuth2 process
    1. (the user will be prompted by Canvas to allow OnTask to access their Canvas account)
    1. OnTask should store the token and refresh token for later use.
1. Display a page similar to the "Send Emails for action" page
    1. This page should prompt the user to enter a subject for the message, and choose a column from the data table that corresponds to the recipients Canvas IDs.
    (I've heard that the allowable content types of Canvas messages is fairly constrained, so perhaps this page should also include a warning or suggestion to revise the message, if it currently contains unsupported content).
    1. Clicking "send" should:
        1. Attempt to send the messages via the Canvas API:
            1. If the messages fail to send due to the access_token expiring:
                1. Use the refresh token to acquire a new access_token and re-try sending.

Thoughts?

**Comment by abelardopardo** [comment]
Some initial steps to execute a new action type that sends a JSON object to a given URL with a given Token. This will be included in the next release, and some of the functionality can be used to tackle this one. We are getting closer..l.

**Comment by abelardopardo** [comment]
Good initial sketch. I'm about to push out the initial functionality to have JSON actions. The functionality you are describing would be a refinement for this one but specifically to talk to Canvas. The exchange of credentials and obtaining the token is the delicate part. I think I have enough to sketch the first skeleton...

**Comment by craigdsthompson** [comment]
Our work to date on this issue is here: https://github.com/ubc/ontask_b/tree/canvas-api-conversations

We've used https://github.com/Harvard-University-iCommons/django-canvas-oauth to handle authentication and tokens.

**Comment by abelardopardo** [comment]
Thanks Craig. I'll get back to you for integration. I think this is a very neat feature...

**Comment by abelardopardo** [comment]
After some further conversations, a greatly simplified approach entails:
1) User gets the token from Canvas from "Account" -> Settings -> Approved Integrations -> New access token
2) OnTask offers site configuration with a list of Canvas API entrypoints
3) User write personalized canvas email text (interface similar to the existing one for personalized text)
4) User selects (if applicable) the API entry point
5) User introduces the token (obtained in step 1). OnTask DOES NOT record that token
6) Emails get sent to Canvas API properly encoded as JSON payload

Pros: Does not require OAuth2, simplifies the steps in OnTask

Cons: Assumes that user has access to Canvas Token, requires user to store and paste that token repeteadly.

**Comment by craigdsthompson** [comment]
Unfortunately, Instructure states in the API documentation [here](https://canvas.instructure.com/doc/api/file.oauth.html#manual-token-generation) that 

> asking any other user to manually generate a token and enter it into your application is a violation of Canvas' terms of service

and 

> Applications in use by multiple users **MUST* use OAuth to obtain tokens*

So, I think a Canvas integration should use OAuth2, rather than manually generated tokens. I appreciate that this does add some complexity to OnTask.

**Comment by abelardopardo** [comment]
Thanks for the link to the documentation. Very timely. I didn't know that Canvas was offering that functionality only for testing purposes. The functionality to send the message using the token will still be valid, but we'll have to take a look to how to go through the OAuth2 loop. We have done a bit of that exploration in the past and showed that it would be better to migrate to Djang 2 to use the right Oauth2 libraries. I'll keep the ticket open and report progress further down the line.

**Comment by abelardopardo** [comment]
One more question. Any ideas how to test the Oauth2 flow with Canvas? Any chance you would be willing to test it? As far as I can tell, you need to register the external application with Canvas in order to use it. This may be a bottleneck. Any ideas?

**Comment by anthonysymons** [comment]
Hi Abelardo and Craig. I am Anthony from U of Adelaide and we are also interested in this feature. We have a rough implementation in an old version of ontask_b which we have been testing (with tokens) and we are looking only to deliver messages via canvas and do not want to provide users with the option to send emails directly (maybe this could be a feature toggle)?. We would be willing to help test and we possibly could cut some code but we are not a python team. It would be great to have the functionality in mainstream.

**Comment by anthonysymons** [comment]
@abelardopardo you may be able to test against a canvas VM https://bitnami.com/stack/canvaslms/virtual-machine

**Comment by abelardopardo** [comment]
Good pointer. I've gone down this path before with another appliance from bitnami to test edX. Should work.

**Comment by craigdsthompson** [comment]
@abelardopardo Yes, I/we (UBC) are able to help with testing.

As a reminder, we also have a working implementation of the Canvas/OnTask Oauth2 workflow (repo linked above). It's not PR-ready, but feel free to take from our work, if it's useful.

**Comment by abelardopardo** [comment]
Yes, I'll try to put all these pieces together. Thanks!

**Comment by abelardopardo** [comment]
Just a heads up. This functionality will be part of a next major release in which the platform is migrating to Python 3 and Django 2. It may not be a trivial migration as there are quite a few changes in the underlying libraries.

**Comment by abelardopardo** [comment]
Hello @craigdsthompson @anthonysymons 

I just pushed a commit with label "Version_4_Beta_Canvas_Email" with the initial version of the functionality to send personalized emails through Canvas. Before deploying this version of the platform you have to take into account that we have migrated to Django 2 and Pythong 3. The new deployment may be a bit challenging to achieve, but I think it is  worth the effort.

The new Canvas email functionality requires first some configuration in the local.env file (parameters that are specific to each instance). See the documentation for more details. Once enabled, the platform will offer a new type of action (Personalized Canvas Email). The messages are sent asynchronously through the queueing system. The logs created throughout this step are written to the file celery.log and also as part of the logs in OnTask itself.

The authentication is done through OAuth2 and requires Canvas to create a token and provide the client ID and client secret so that they are part of the OnTask configuration. As it stands, OnTask is capable of handling more than one Canvas instance.

The credentials are attached to the user and can be deleted through the user profile page.

I have done some preliminary testing using the bitnami virtual machine with the community version installed. The OAuth2 cycle was properly executed and the emails appeared in the canvas email accounts of the students. Having said this, we know need you to run further tests and make sure it is tightly integreated with a corporate instance.

**Comment by abelardopardo** [comment]
New Beta version. The tag "Version_4_Beta_Canvas_Email" has been moved now to include PR #110, #111 and #113.

**Comment by anthonysymons** [comment]
Hi, we are planning to install and test V4, in the first weeks of 2019. Sorry I cant have an update sooner, but we'll pull the latest then, test and report back. Thanks!

**Comment by abelardopardo** [comment]
Issue fixed in release 4.0

**Comment by firasm** [comment]
update: Three classes have successfully sent messages through Canvas using V4 at UBC. 

Things seem to be working well! No major issues.

**Comment by abelardopardo** [comment]
Fantastic news! Thanks for the update. I'll be reaching out to you to write up a "success story" with OnTask
