### ISSUE TITLE
Any interest is using Docker for a developement environment?

### ISSUE THREAD

**Issue by andrew-gardener** [abelardopardo/ontask_b#81]
I've already done some work around getting an OnTask development environment setup for my own use https://github.com/ubc/ontask_b/commit/ef60cf88134ecc536645892fd1f7668088e0307f (note production mode doesn't work at the moment)

Is there any interest in a PR?

**Comment by abelardopardo** [comment]
Yes. Stay tunned and I'll either flick to you what I've got so far (full deployment) or directly include in source tree for your review.

**Comment by abelardopardo** [comment]
Scripts provided in Version 5
