### ISSUE TITLE
http cdn js/css links

### ISSUE THREAD

**Issue by whol019** [abelardopardo/ontask_b#85]
Hi
Our university web servers use mostly https url only.
There are some template files that use http urls for javascript and css ant that causes browser to block http resources if server using https url.

All these links could be changed to be without http: in the url
i.e.
//cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css
//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js
//cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js
....

Also in development mode, I need to add DEBUG=TRUE  in local.env, to make it run without issue.
otherwise it seems to get some error like
'djdt is not a registered namespace'

Hope this help
Wen

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0
