### ISSUE TITLE
Unable to delete filters 

### ISSUE THREAD

**Issue by radhikavm** [abelardopardo/ontask_b#86]
Hi Abelardo

<img width="1287" alt="screen shot 2018-09-18 at 9 44 31 am" src="https://user-images.githubusercontent.com/1100207/45656214-8a1bda80-bb27-11e8-88b6-49593df3344e.png">

Tend to get an 404 error for https://cdn.datatables.net/plug-ins/1.10.19/i18n/undefined.json as soon as I login to ontask.

Not sure if the above has anything to do with the issue though.

**Comment by abelardopardo** [comment]
This is a glitch in one javascript loading the language of your browser. Fixed.

**Comment by abelardopardo** [comment]
Solved in Version B.3.0.0
