### ISSUE TITLE
v3.0  settings/base.py   'django.contrib.sessions.middleware.SessionMiddleware' load twice

### ISSUE THREAD

**Issue by whol019** [abelardopardo/ontask_b#89]
Hi Abelardo
In version 3 I have difficulty to go to 'upload or merge data' page.
After some test, found out the SessionMiddleware loaded twice in base.py MIDDLEWARE_CLASSES.
Mark out the 2nd SessionMiddleware in base.py( line 142 ), then dataops/uploadmerge page load normally
We are using custom remote user middleware.
Hope this help
Wen

**Comment by abelardopardo** [comment]
Fixed in V3.0.0
