### ISSUE TITLE
TIME_ZONE error

### ISSUE THREAD

**Issue by radhikavm** [abelardopardo/ontask_b#90]
When I update the TIME_ZONE='Australia/Sydney'  or TIME_ZONE=Australia/Sydney tend to get the following errors:

    ```File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/django/conf/__init__.py", line 137, in 
        __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
    ValueError: Incorrect timezone setting: Austalia/Sydney```

**Comment by abelardopardo** [comment]
The copy paste of the error reads "Austalia". There is a missing 'r' could that be it?

**Comment by radhikavm** [comment]
Yes Abelardo, the missing r was the issue, thanks
